/*
*   All config values specified here will be merged with main config and will override its values
*
*/
/* global VBET5 */
VBET5.constant('SkinConfig', {
    'main': {
        siteTitle: {
            "eng": "exbinog.com",
            "cze": "exbinog.com",
            "ita": "exbinog.com",
            "ger": "exbinog.com",
            "rus": "exbinog.com",
            "por": "exbinog.com",
            "spa": "exbinog.com",
            "pol": "exbinog.com"
        },
        site_name: "exbinog.com",
        site_id: "55",
        skin: 'exbinog.com',
        casinoEnabled: true,
        pokerEnabled: false,
		googleAnalyticsId: 'UA-55247423-1',
        liveDealerEnabled: true,
        financialsEnabled: true,
        skillgamesEnabled: false,
        poolBettingEnabled: true, //enable pool betting
        redirectOnTablets: 'http://tablet.exbinog.com/',
        videoEnabled: false,
        facebookUrl: "https://www.facebook.com/betdadofficial",
        googlePlusUrl: "https://plus.google.com/u/0/102929530252862627272",
        twitterAccount: 'betdad_official',
        twitterHashTag: 'betdad',
        youtubeUrl: 'https://www.youtube.com/channel/UCLLisvln7cYIGtqa6zDKQxQ',
        about_company_text: {
            'eng' : '<div id="preview"><div id="egm"><img id="egm_cooperation_logo" src="//license.e-gambling.me/0016/license.png" alt="In cooperation with E-Gambling Montenegro."><p id="egm_prolog">www.exbinog.com is operated by Exclusive Gaming Limited City Rd. 152, EC1V 2NX London, UK and is licensed and regulated by the government of Montenegro.</p><p id="egm_certifies"> E-Gambling Montenegro d.o.o. (Podgorica, Moskovska br. 65., reg. no. 5-0615951) hereby certifies that under the concession (serial no. AA 0546, numeric no. 117-01/12) and approval (no. 02/01-376/3), organize and operate games on chance in Montenegro on website www.exbinog.com, in accordance with the Agreement on management and financial cooperation, concluded between E-Gambling Montenegro d.o.o. and Exclusive Limited d.o.o. (Podgorica, Cetinjski put bb, reg. no. 5-0668456, TIN: 02947285) on 26 August, 2013.</p><p id="egm_details">More details about the license, E-gambling Montenegro and handling of complaints: www.e-gambling.me</p></div></div>',
            'cze' : '<div id="preview"><div id="egm"><img id="egm_cooperation_logo" src="//license.e-gambling.me/0016/license.png" alt="In cooperation with E-Gambling Montenegro."><p id="egm_prolog">www.exbinog.com is operated by Exclusive Gaming Limited City Rd. 152, EC1V 2NX London, UK and is licensed and regulated by the government of Montenegro.</p><p id="egm_certifies"> E-Gambling Montenegro d.o.o. (Podgorica, Moskovska br. 65., reg. no. 5-0615951) hereby certifies that under the concession (serial no. AA 0546, numeric no. 117-01/12) and approval (no. 02/01-376/3), organize and operate games on chance in Montenegro on website www.exbinog.com, in accordance with the Agreement on management and financial cooperation, concluded between E-Gambling Montenegro d.o.o. and Exclusive Limited d.o.o. (Podgorica, Cetinjski put bb, reg. no. 5-0668456, TIN: 02947285) on 26 August, 2013.</p><p id="egm_details">More details about the license, E-gambling Montenegro and handling of complaints: www.e-gambling.me</p></div></div>',
            'ita' : '<div id="preview"><div id="egm"><img id="egm_cooperation_logo" src="//license.e-gambling.me/0016/license.png" alt="In cooperation with E-Gambling Montenegro."><p id="egm_prolog">www.exbinog.com is operated by Exclusive Gaming Limited City Rd. 152, EC1V 2NX London, UK and is licensed and regulated by the government of Montenegro.</p><p id="egm_certifies"> E-Gambling Montenegro d.o.o. (Podgorica, Moskovska br. 65., reg. no. 5-0615951) hereby certifies that under the concession (serial no. AA 0546, numeric no. 117-01/12) and approval (no. 02/01-376/3), organize and operate games on chance in Montenegro on website www.exbinog.com, in accordance with the Agreement on management and financial cooperation, concluded between E-Gambling Montenegro d.o.o. and Exclusive Limited d.o.o. (Podgorica, Cetinjski put bb, reg. no. 5-0668456, TIN: 02947285) on 26 August, 2013.</p><p id="egm_details">More details about the license, E-gambling Montenegro and handling of complaints: www.e-gambling.me</p></div></div>',
            'ger' : '<div id="preview"><div id="egm"><img id="egm_cooperation_logo" src="//license.e-gambling.me/0016/license.png" alt="In cooperation with E-Gambling Montenegro."><p id="egm_prolog">www.exbinog.com is operated by Exclusive Gaming Limited City Rd. 152, EC1V 2NX London, UK and is licensed and regulated by the government of Montenegro.</p><p id="egm_certifies"> E-Gambling Montenegro d.o.o. (Podgorica, Moskovska br. 65., reg. no. 5-0615951) hereby certifies that under the concession (serial no. AA 0546, numeric no. 117-01/12) and approval (no. 02/01-376/3), organize and operate games on chance in Montenegro on website www.exbinog.com, in accordance with the Agreement on management and financial cooperation, concluded between E-Gambling Montenegro d.o.o. and Exclusive Limited d.o.o. (Podgorica, Cetinjski put bb, reg. no. 5-0668456, TIN: 02947285) on 26 August, 2013.</p><p id="egm_details">More details about the license, E-gambling Montenegro and handling of complaints: www.e-gambling.me</p></div></div>',
            'rus' : '<div id="preview"><div id="egm"><img id="egm_cooperation_logo" src="//license.e-gambling.me/0016/license.png" alt="In cooperation with E-Gambling Montenegro."><p id="egm_prolog">www.exbinog.com is operated by Exclusive Gaming Limited City Rd. 152, EC1V 2NX London, UK and is licensed and regulated by the government of Montenegro.</p><p id="egm_certifies"> E-Gambling Montenegro d.o.o. (Podgorica, Moskovska br. 65., reg. no. 5-0615951) hereby certifies that under the concession (serial no. AA 0546, numeric no. 117-01/12) and approval (no. 02/01-376/3), organize and operate games on chance in Montenegro on website www.exbinog.com, in accordance with the Agreement on management and financial cooperation, concluded between E-Gambling Montenegro d.o.o. and Exclusive Limited d.o.o. (Podgorica, Cetinjski put bb, reg. no. 5-0668456, TIN: 02947285) on 26 August, 2013.</p><p id="egm_details">More details about the license, E-gambling Montenegro and handling of complaints: www.e-gambling.me</p></div></div>',
            'por' : '<div id="preview"><div id="egm"><img id="egm_cooperation_logo" src="//license.e-gambling.me/0016/license.png" alt="In cooperation with E-Gambling Montenegro."><p id="egm_prolog">www.exbinog.com is operated by Exclusive Gaming Limited City Rd. 152, EC1V 2NX London, UK and is licensed and regulated by the government of Montenegro.</p><p id="egm_certifies"> E-Gambling Montenegro d.o.o. (Podgorica, Moskovska br. 65., reg. no. 5-0615951) hereby certifies that under the concession (serial no. AA 0546, numeric no. 117-01/12) and approval (no. 02/01-376/3), organize and operate games on chance in Montenegro on website www.exbinog.com, in accordance with the Agreement on management and financial cooperation, concluded between E-Gambling Montenegro d.o.o. and Exclusive Limited d.o.o. (Podgorica, Cetinjski put bb, reg. no. 5-0668456, TIN: 02947285) on 26 August, 2013.</p><p id="egm_details">More details about the license, E-gambling Montenegro and handling of complaints: www.e-gambling.me</p></div></div>',
            'spa' : '<div id="preview"><div id="egm"><img id="egm_cooperation_logo" src="//license.e-gambling.me/0016/license.png" alt="In cooperation with E-Gambling Montenegro."><p id="egm_prolog">www.exbinog.com is operated by Exclusive Gaming Limited City Rd. 152, EC1V 2NX London, UK and is licensed and regulated by the government of Montenegro.</p><p id="egm_certifies"> E-Gambling Montenegro d.o.o. (Podgorica, Moskovska br. 65., reg. no. 5-0615951) hereby certifies that under the concession (serial no. AA 0546, numeric no. 117-01/12) and approval (no. 02/01-376/3), organize and operate games on chance in Montenegro on website www.exbinog.com, in accordance with the Agreement on management and financial cooperation, concluded between E-Gambling Montenegro d.o.o. and Exclusive Limited d.o.o. (Podgorica, Cetinjski put bb, reg. no. 5-0668456, TIN: 02947285) on 26 August, 2013.</p><p id="egm_details">More details about the license, E-gambling Montenegro and handling of complaints: www.e-gambling.me</p></div></div>',
            'pol' : '<div id="preview"><div id="egm"><img id="egm_cooperation_logo" src="//license.e-gambling.me/0016/license.png" alt="In cooperation with E-Gambling Montenegro."><p id="egm_prolog">Exbinog.com jest licencjonowane oraz regulowane przez rząd Montenegro.</p><p id="egm_certifies">E-Gambling Montenegro d.o.o. (Podgorica, Moskovska br. 65., reg. no. 5-0615951) zaświadcza, że w ramach koncesji (serial no. AA 0546, numeric no. 117-01/12) wydało zezwolenie (no. 02/01-376/3) na organizowanie i prowadzenie gier losowych przez Exbinog.com zgodnie z porozumieniem w sprawie zarządzania i współpracy finansowej, zawartym pomiędzy E-Gambling Montenegro d.o.o. a firmą Exclusive Limited d.o.o. (Podgorica, Cetinjski put bb, reg. no. 5-0668456, TIN: 02947285) dnia 26 sierpnia 2013.</p><p id="egm_details">Więcej szczegółów na temat licencji: www.e-gambling.me<br>Strony serwisu w języku polskim są skierowane wyłącznie do osób, które chcą skorzystać z naszych usług w języku polskim poza terytorium Rzeczypospolitej Polskiej.</p></div></div>'
        },

        availableLanguages: {
            '@replace': true, // this means that object won't be merged with 'parent object', but will replace it
            'eng' : { 'short': 'EN', 'full': "English"},
            'pol' : { 'short': 'PL', 'full': "Polski"},
            'cze' : { 'short': 'CZ', 'full': "Český"},
            'ger' : { 'short': 'DE', 'full': "Deutsch"},
            'ita' : { 'short': 'IT', 'full': "Italiano"},
            'por' : { 'short': 'PT', 'full': "Português"},
            'spa' : { 'short': 'ES', 'full': "Español"},
            'rus' : { 'short': 'RU', 'full': "Русский"}
        },
        registration: {
            defaultCurrency: 'USD',
            restrictedCountries: {},
            termsLink: true
        },
        liveChat: {
            wId: 34,
            enableChat: '0', //this means only FAQ will be shown in widget
            langMapping: { // if live chat is not available in some language we will use another
                'it' : 'en',
                'de' : 'en',
                'cz' : 'en',
                'pt' : 'en',
                'es' : 'en',
                'ru' : 'en'
            },
            title: {
                'en' : 'FAQ / MESSENGER',
                'pl' : 'FAQ / ZADAJ PYTANIE',
                'cz' : 'FAQ / MESSENGER',
                'de' : 'FAQ / MESSENGER',
                'it' : 'FAQ / MESSENGER',
                'pt' : 'FAQ / MESSENGER',
                'es' : 'FAQ / MESSENGER',
                'ru' : 'FAQ / MESSENGER'
}
        },
        availableCurrencies: ['USD', 'EUR', 'GBP', 'PLN', 'CZK'],
        balanceFractionSize: 0, //number of decimal places to round the balance value to(when displaying)
        enableNews: true, // enable news on sport page
        enableBannerUnderBetslip: false, // enable banner under the betslip,
        disableFooterNav: false, // disable wordpress content in footer,
        disableHomepageNews: false,
        poweredByInFooter: -1,
        copyrightSince: 2014
    },
    'env': {
        showFifaCountdown: false
    },
    'swarm': {
        url: [{ url: "http://swarm.exbinog.com:8084/"}],
        websocket: [{ url: "ws://swarm.exbinog.com:8084/"}]
    },
    xDomainSlaves: '{"http://swarm.exbinog.com:8084" : "/xdomain-proxy.html"}', //has to be JSON string

    'payments': [
        {
            name: 'cashbill',
            canDeposit: true,
            canWithdraw: true,
            order: 3,
            depositInfoTextKey: 'deposit_info_cashbill', // translate##deposit_info_cashbill##
//            onlyInfoTextOnWithdraw: true, // means that only text will be shown, no amount and no withdraw button
            depositInfoText: {
                eng : "CashBill is a global settlement system enabling internet users to conduct safe money transfers in real time. Funds will be transfered to your exbinog account immediately. There are no fees for using this payment method. Transfers don't have a minimum and/or a maximum value. To deposit funds into your exbinog account using CashBill, simply press deposit after entering your login & amount you want to transfer below. You will be redirected to CashBill to complete your transaction. Please note that you must have bank account in PLN currency to use this payment method.",
                pol : "CashBill jest globalnym systemem rozliczeniowym, umożliwiającym użytkownikom przeprowadzanie bezpiecznych transferów pieniędzy w czasie rzeczywistym. Środki zostaną natychmiast przekazane na Twoje konto exbinog. Nie pobieramy żadnych opłat za korzystanie z tej metody płatności. Transfery nie mają minimalnej lub maksymalnej wartości. Aby wpłacić pieniądze na swoje konto exbinog używając CashBill, wystarczy nacisnąć depozyt oraz wpisać kwotę, którą chcesz zdeponować. Zostaniesz przekierowany na stronę CashBill aby zakończyć transakcję. Metoda ta dostępna jest tylko dla użytkowników posiadających konto bankowe w walucie PLN.",
                cze : "CashBill is a global settlement system enabling internet users to conduct safe money transfers in real time. Funds will be transfered to your exbinog account immediately. There are no fees for using this payment method. Transfers don't have a minimum and/or a maximum value. To deposit funds into your exbinog account using CashBill, simply press deposit after entering your login & amount you want to transfer below. You will be redirected to CashBill to complete your transaction. Please note that you must have bank account in PLN currency to use this payment method.",
                ger : "CashBill is a global settlement system enabling internet users to conduct safe money transfers in real time. Funds will be transfered to your exbinog account immediately. There are no fees for using this payment method. Transfers don't have a minimum and/or a maximum value. To deposit funds into your exbinog account using CashBill, simply press deposit after entering your login & amount you want to transfer below. You will be redirected to CashBill to complete your transaction. Please note that you must have bank account in PLN currency to use this payment method.",
                rus : "CashBill is a global settlement system enabling internet users to conduct safe money transfers in real time. Funds will be transfered to your exbinog account immediately. There are no fees for using this payment method. Transfers don't have a minimum and/or a maximum value. To deposit funds into your exbinog account using CashBill, simply press deposit after entering your login & amount you want to transfer below. You will be redirected to CashBill to complete your transaction. Please note that you must have bank account in PLN currency to use this payment method.",
                spa : "CashBill is a global settlement system enabling internet users to conduct safe money transfers in real time. Funds will be transfered to your exbinog account immediately. There are no fees for using this payment method. Transfers don't have a minimum and/or a maximum value. To deposit funds into your exbinog account using CashBill, simply press deposit after entering your login & amount you want to transfer below. You will be redirected to CashBill to complete your transaction. Please note that you must have bank account in PLN currency to use this payment method.",
                por : "CashBill is a global settlement system enabling internet users to conduct safe money transfers in real time. Funds will be transfered to your exbinog account immediately. There are no fees for using this payment method. Transfers don't have a minimum and/or a maximum value. To deposit funds into your exbinog account using CashBill, simply press deposit after entering your login & amount you want to transfer below. You will be redirected to CashBill to complete your transaction. Please note that you must have bank account in PLN currency to use this payment method.",
                ita : "CashBill is a global settlement system enabling internet users to conduct safe money transfers in real time. Funds will be transfered to your exbinog account immediately. There are no fees for using this payment method. Transfers don't have a minimum and/or a maximum value. To deposit funds into your exbinog account using CashBill, simply press deposit after entering your login & amount you want to transfer below. You will be redirected to CashBill to complete your transaction. Please note that you must have bank account in PLN currency to use this payment method."
            },
            withdrawInfoText: {
                eng : "In order to ensure that our Clients’ money is safe, we ask for documents confirming personal data for the first withdrawal. This applies to all the registered accounts.<br /> We accept the following documents:<br /> <br /> - personal ID,<br /> - driver’s license,<br /> - passport.<br /> <br /> 1) Please send us a scan of a document with photo and data that matches your account.<br /> 2) Please send us a utility bill confirming your address (not older than 3 months)<br /> 3) Please send us a bank statement confirming that the bank account you want the money to be withdrawn to is yours.<br /> <br /> The documents should be scanned and sent to payments@exbinog.com .",
                pol : "Ze względów bezpieczeństwa, wymagamy dokumentów potwierdzających dane osobowe przy pierwszej wypłacie środków. Odnosi się to do wszystkich zarejestrowanych użytkowników.<br /> <br /> Akceptujemy następujące dokumenty: <br /> <br /> - dowód osobisty <br /> - Prawo jazdy, <br /> - Paszport. <br /> <br /> 1) Przygotuj skan dokumentu ze zdjęciem, z danymi, które potwierdzają Twoje dane na koncie w exbinog.com .<br /> 2) Przygotuj skan rachunku potwierdzającego Twój adres (rachunek za prąd, telefon, usługi komunalne). Rachunek nie może być starszy niż 3 miesiące.<br /> 3) Przygotuj dokumenty bankowy potwierdzający, że rachunek na który wypłacasz środki należy do Ciebie.<br /> <br /> Proszę przesłać dokumenty na adres payments@exbinog.com.",
                cze : "In order to ensure that our Clients’ money is safe, we ask for documents confirming personal data for the first withdrawal. This applies to all the registered accounts.<br /> We accept the following documents:<br /> <br /> - personal ID,<br /> - driver’s license,<br /> - passport.<br /> <br /> 1) Please send us a scan of a document with photo and data that matches your account.<br /> 2) Please send us a utility bill confirming your address (not older than 3 months)<br /> 3) Please send us a bank statement confirming that the bank account you want the money to be withdrawn to is yours.<br /> <br /> The documents should be scanned and sent to payments@exbinog.com .",
                ger : "In order to ensure that our Clients’ money is safe, we ask for documents confirming personal data for the first withdrawal. This applies to all the registered accounts.<br /> We accept the following documents:<br /> <br /> - personal ID,<br /> - driver’s license,<br /> - passport.<br /> <br /> 1) Please send us a scan of a document with photo and data that matches your account.<br /> 2) Please send us a utility bill confirming your address (not older than 3 months)<br /> 3) Please send us a bank statement confirming that the bank account you want the money to be withdrawn to is yours.<br /> <br /> The documents should be scanned and sent to payments@exbinog.com .",
                rus : "In order to ensure that our Clients’ money is safe, we ask for documents confirming personal data for the first withdrawal. This applies to all the registered accounts.<br /> We accept the following documents:<br /> <br /> - personal ID,<br /> - driver’s license,<br /> - passport.<br /> <br /> 1) Please send us a scan of a document with photo and data that matches your account.<br /> 2) Please send us a utility bill confirming your address (not older than 3 months)<br /> 3) Please send us a bank statement confirming that the bank account you want the money to be withdrawn to is yours.<br /> <br /> The documents should be scanned and sent to payments@exbinog.com .",
                spa : "In order to ensure that our Clients’ money is safe, we ask for documents confirming personal data for the first withdrawal. This applies to all the registered accounts.<br /> We accept the following documents:<br /> <br /> - personal ID,<br /> - driver’s license,<br /> - passport.<br /> <br /> 1) Please send us a scan of a document with photo and data that matches your account.<br /> 2) Please send us a utility bill confirming your address (not older than 3 months)<br /> 3) Please send us a bank statement confirming that the bank account you want the money to be withdrawn to is yours.<br /> <br /> The documents should be scanned and sent to payments@exbinog.com .",
                por : "In order to ensure that our Clients’ money is safe, we ask for documents confirming personal data for the first withdrawal. This applies to all the registered accounts.<br /> We accept the following documents:<br /> <br /> - personal ID,<br /> - driver’s license,<br /> - passport.<br /> <br /> 1) Please send us a scan of a document with photo and data that matches your account.<br /> 2) Please send us a utility bill confirming your address (not older than 3 months)<br /> 3) Please send us a bank statement confirming that the bank account you want the money to be withdrawn to is yours.<br /> <br /> The documents should be scanned and sent to payments@exbinog.com .",
                ita : "In order to ensure that our Clients’ money is safe, we ask for documents confirming personal data for the first withdrawal. This applies to all the registered accounts.<br /> We accept the following documents:<br /> <br /> - personal ID,<br /> - driver’s license,<br /> - passport.<br /> <br /> 1) Please send us a scan of a document with photo and data that matches your account.<br /> 2) Please send us a utility bill confirming your address (not older than 3 months)<br /> 3) Please send us a bank statement confirming that the bank account you want the money to be withdrawn to is yours.<br /> <br /> The documents should be scanned and sent to payments@exbinog.com ."
            }

        },
        {
            name: 'skrill',
            canDeposit: true,
            canWithdraw: true,
            order: 2,
            // translate##deposit_info_skrill##   <--- these are special comments that tell translation
            // generation script that key inside hashes has to be included in translation table
            depositInfoText: {
                eng : "<p>Skrill is a secure, convenient and affordable way to send and receive money worldwide.  Supported currencies include  USD,EUR,GBP,PLN,CZK.  Funds will be transferred to your account immediately.</p><p>There are no fees for using this payment method.</p><p>Transfers don&#96;t have a minimum and/or a maximum value.</p><p>To deposit funds into your Exbinog account using Skrill, simply press deposit after entering the e-mail address registered with Skrill and the amount you want to transfer below. You will be redirected to Skrill to complete your transaction.</p>",
                pol : "<p>Skrill jest bezpiecznym i wygodnym sposobem na wysyłanie i otrzymywanie pieniędzy na całym świecie. Obsługiwane są wszystkie waluty. Środki będą natychmiast przekazywane na Twoje konto w Exbinog.<br>Nie pobieramy żadnych opłat za korzystanie z tej metody płatności.<br>Transfery nie mają minimalnej lub maksymalnej wartości.<br>Aby wpłacić pieniądze na swoje konto za pomocą Skrill, wystarczy nacisnąć depozyt po wprowadzeniu adresu e-mail zarejestrowanego w Skrill oraz kwotę, którą chcesz przekazać poniżej. Zostaniesz przekierowany do Skrill, aby dokończyć transakcję.<br></p>",
                cze : "<p>Skrill is a secure, convenient and affordable way to send and receive money worldwide.  Supported currencies include  USD,EUR,GBP,PLN,CZK.  Funds will be transferred to your account immediately.</p><p>There are no fees for using this payment method.</p><p>Transfers don&#96;t have a minimum and/or a maximum value.</p><p>To deposit funds into your Exbinog account using Skrill, simply press deposit after entering the e-mail address registered with Skrill and the amount you want to transfer below. You will be redirected to Skrill to complete your transaction.</p>",
                ger : "<p>Skrill is a secure, convenient and affordable way to send and receive money worldwide.  Supported currencies include  USD,EUR,GBP,PLN,CZK.  Funds will be transferred to your account immediately.</p><p>There are no fees for using this payment method.</p><p>Transfers don&#96;t have a minimum and/or a maximum value.</p><p>To deposit funds into your Exbinog account using Skrill, simply press deposit after entering the e-mail address registered with Skrill and the amount you want to transfer below. You will be redirected to Skrill to complete your transaction.</p>",
                rus : "<p>Skrill is a secure, convenient and affordable way to send and receive money worldwide.  Supported currencies include  USD,EUR,GBP,PLN,CZK.  Funds will be transferred to your account immediately.</p><p>There are no fees for using this payment method.</p><p>Transfers don&#96;t have a minimum and/or a maximum value.</p><p>To deposit funds into your Exbinog account using Skrill, simply press deposit after entering the e-mail address registered with Skrill and the amount you want to transfer below. You will be redirected to Skrill to complete your transaction.</p>",
                spa : "<p>Skrill is a secure, convenient and affordable way to send and receive money worldwide.  Supported currencies include  USD,EUR,GBP,PLN,CZK.  Funds will be transferred to your account immediately.</p><p>There are no fees for using this payment method.</p><p>Transfers don&#96;t have a minimum and/or a maximum value.</p><p>To deposit funds into your Exbinog account using Skrill, simply press deposit after entering the e-mail address registered with Skrill and the amount you want to transfer below. You will be redirected to Skrill to complete your transaction.</p>",
                por : "<p>Skrill is a secure, convenient and affordable way to send and receive money worldwide.  Supported currencies include  USD,EUR,GBP,PLN,CZK.  Funds will be transferred to your account immediately.</p><p>There are no fees for using this payment method.</p><p>Transfers don&#96;t have a minimum and/or a maximum value.</p><p>To deposit funds into your Exbinog account using Skrill, simply press deposit after entering the e-mail address registered with Skrill and the amount you want to transfer below. You will be redirected to Skrill to complete your transaction.</p>",
                ita : "<p>Skrill is a secure, convenient and affordable way to send and receive money worldwide.  Supported currencies include  USD,EUR,GBP,PLN,CZK.  Funds will be transferred to your account immediately.</p><p>There are no fees for using this payment method.</p><p>Transfers don&#96;t have a minimum and/or a maximum value.</p><p>To deposit funds into your Exbinog account using Skrill, simply press deposit after entering the e-mail address registered with Skrill and the amount you want to transfer below. You will be redirected to Skrill to complete your transaction.</p>"
            },
            withdrawInfoText: {
                eng : "In order to ensure that our Clients’ money is safe, we ask for documents confirming personal data for the first withdrawal. This applies to all the registered accounts. <br /> <br /> We accept the following documents:<br /> <br /> - personal ID,<br /> - driver’s license,<br /> - passport.<br /> <br /> Please send us a scan of a document with photo and data that matches your account.<br /> <br /> The documents should be scanned and sent to payments@exbinog.com",
                pol : "Ze względów bezpieczeństwa, wymagamy dokumentów potwierdzających dane osobowe przy pierwszej wypłacie środków. Odnosi się to do wszystkich zarejestrowanych użytkowników.<br /> <br /> Akceptujemy następujące dokumenty: <br /> <br /> - dowód osobisty <br /> - Prawo jazdy, <br /> - Paszport. <br /> <br /> 1) Przygotuj skan dokumentu ze zdjęciem, z danymi, które potwierdzają Twoje dane na koncie w exbinog.com .<br /> 2) Przygotuj skan rachunku potwierdzającego Twój adres (rachunek za prąd, telefon, usługi komunalne). Rachunek nie może być starszy niż 3 miesiące. </p><p>Proszę przesłać dokumenty na adres payments@exbinog.com</p>",
                cze : "In order to ensure that our Clients’ money is safe, we ask for documents confirming personal data for the first withdrawal. This applies to all the registered accounts. <br /> <br /> We accept the following documents:<br /> <br /> - personal ID,<br /> - driver’s license,<br /> - passport.<br /> <br /> Please send us a scan of a document with photo and data that matches your account.<br /> <br /> The documents should be scanned and sent to payments@exbinog.com",
                ger : "In order to ensure that our Clients’ money is safe, we ask for documents confirming personal data for the first withdrawal. This applies to all the registered accounts. <br /> <br /> We accept the following documents:<br /> <br /> - personal ID,<br /> - driver’s license,<br /> - passport.<br /> <br /> Please send us a scan of a document with photo and data that matches your account.<br /> <br /> The documents should be scanned and sent to payments@exbinog.com",
                rus : "In order to ensure that our Clients’ money is safe, we ask for documents confirming personal data for the first withdrawal. This applies to all the registered accounts. <br /> <br /> We accept the following documents:<br /> <br /> - personal ID,<br /> - driver’s license,<br /> - passport.<br /> <br /> Please send us a scan of a document with photo and data that matches your account.<br /> <br /> The documents should be scanned and sent to payments@exbinog.com",
                spa : "In order to ensure that our Clients’ money is safe, we ask for documents confirming personal data for the first withdrawal. This applies to all the registered accounts. <br /> <br /> We accept the following documents:<br /> <br /> - personal ID,<br /> - driver’s license,<br /> - passport.<br /> <br /> Please send us a scan of a document with photo and data that matches your account.<br /> <br /> The documents should be scanned and sent to payments@exbinog.com",
                por : "In order to ensure that our Clients’ money is safe, we ask for documents confirming personal data for the first withdrawal. This applies to all the registered accounts. <br /> <br /> We accept the following documents:<br /> <br /> - personal ID,<br /> - driver’s license,<br /> - passport.<br /> <br /> Please send us a scan of a document with photo and data that matches your account.<br /> <br /> The documents should be scanned and sent to payments@exbinog.com",
                ita : "In order to ensure that our Clients’ money is safe, we ask for documents confirming personal data for the first withdrawal. This applies to all the registered accounts. <br /> <br /> We accept the following documents:<br /> <br /> - personal ID,<br /> - driver’s license,<br /> - passport.<br /> <br /> Please send us a scan of a document with photo and data that matches your account.<br /> <br /> The documents should be scanned and sent to payments@exbinog.com"
            },
//            onlyInfoTextOnWithdraw: true,
            stayInSameTabOnDeposit: false, //will submit external "confirm" form in same tab
            //these external form field values will be set to current URL in app,
            // so when user makes or cancels payment, he'll return to our page
            depositFormFields: [
                {name: 'email', type: 'email', label: 'Email'}  // translate##Email##
            ],
            withdrawFormFields: [
                {name: 'email', type: 'email', label: 'Email', required: true},  // translate##Email##
                {name: 'name', type: 'text', label: 'Name'} // translate##Name##
            ]
        },
        {
            name: 'wirecard',
            canDeposit: true,
            canWithdraw: true,
            order: 4,
            depositInfoText: {
                eng: 'WireCard is a secure, convenient & fast way to deposit funds at your Exbinog account using your credit card. The supported currencies are: EUR, USD, GBP, CZK & PLN. The minimum deposit amount is 10 EUR and the maximum deposit amount is 5000 EUR.<br>Funds will be transfered to your Exbinog account immediately. There are no fees using this payment method. To deposit funds into your Exbinog account using WireCard, simply fill out all the required fields and press the "deposit" button.',
                pol: 'WireCard jest bezpiecznym, wygodnym i szybkim sposobem złożenia depozytu na koncie Exbinog przy użyciu karty kredytowej. Obsługiwane waluty: EUR, USD, GBP, CZK i PLN. Minimalna kwota depozytu wynosi 10 EUR, a maksymalna kwota depozytu wynosi 5000 EUR.<br>Środki zostaną natychmiast przekazane na Twoje konto Exbinog. Nie pobieramy żadnych opłat za złożenie depozytu powyższą metodą płatności. Aby wpłacić pieniądze na swoje konto Exbinog używając Wirecard, wystarczy wypełnić wszystkie wymagane pola, a następnie kliknąć przycisk "Depozyt".',
                cze: 'WireCard is a secure, convenient & fast way to deposit funds at your Exbinog account using your credit card. The supported currencies are: EUR, USD, GBP, CZK & PLN. The minimum deposit amount is 10 EUR and the maximum deposit amount is 5000 EUR.<br>Funds will be transfered to your Exbinog account immediately. There are no fees using this payment method. To deposit funds into your Exbinog account using WireCard, simply fill out all the required fields and press the "deposit" button.',
                ger: 'WireCard is a secure, convenient & fast way to deposit funds at your Exbinog account using your credit card. The supported currencies are: EUR, USD, GBP, CZK & PLN. The minimum deposit amount is 10 EUR and the maximum deposit amount is 5000 EUR.<br>Funds will be transfered to your Exbinog account immediately. There are no fees using this payment method. To deposit funds into your Exbinog account using WireCard, simply fill out all the required fields and press the "deposit" button.',
                rus: 'WireCard is a secure, convenient & fast way to deposit funds at your Exbinog account using your credit card. The supported currencies are: EUR, USD, GBP, CZK & PLN. The minimum deposit amount is 10 EUR and the maximum deposit amount is 5000 EUR.<br>Funds will be transfered to your Exbinog account immediately. There are no fees using this payment method. To deposit funds into your Exbinog account using WireCard, simply fill out all the required fields and press the "deposit" button.',
                spa: 'WireCard is a secure, convenient & fast way to deposit funds at your Exbinog account using your credit card. The supported currencies are: EUR, USD, GBP, CZK & PLN. The minimum deposit amount is 10 EUR and the maximum deposit amount is 5000 EUR.<br>Funds will be transfered to your Exbinog account immediately. There are no fees using this payment method. To deposit funds into your Exbinog account using WireCard, simply fill out all the required fields and press the "deposit" button.',
                por: 'WireCard is a secure, convenient & fast way to deposit funds at your Exbinog account using your credit card. The supported currencies are: EUR, USD, GBP, CZK & PLN. The minimum deposit amount is 10 EUR and the maximum deposit amount is 5000 EUR.<br>Funds will be transfered to your Exbinog account immediately. There are no fees using this payment method. To deposit funds into your Exbinog account using WireCard, simply fill out all the required fields and press the "deposit" button.',
                ita: 'WireCard is a secure, convenient & fast way to deposit funds at your Exbinog account using your credit card. The supported currencies are: EUR, USD, GBP, CZK & PLN. The minimum deposit amount is 10 EUR and the maximum deposit amount is 5000 EUR.<br>Funds will be transfered to your Exbinog account immediately. There are no fees using this payment method. To deposit funds into your Exbinog account using WireCard, simply fill out all the required fields and press the "deposit" button.'
            },
            withdrawInfoText: {
                eng: "In order to ensure that our Clients’ money is safe, we ask for documents confirming personal data for the first withdrawal. This applies to all the registered accounts.<br /> We accept the following documents:<br /> <br /> - personal ID,<br /> - driver’s license,<br /> - passport.<br /> <br /> 1) Please send us a scan of a document with photo and data that matches your account.<br /> 2) Please send us a utility bill confirming your address (not older than 3 months)<br /> 3) Please send us copies of both sides of the card that was used to deposit, with the 8 middle digits in the front and the CVV number at the back concealed.<br /> <br /> The documents should be scanned and sent to payments@exbinog.com .",
                pol: "Ze względów bezpieczeństwa, wymagamy dokumentów potwierdzających dane osobowe przy pierwszej wypłacie środków. Odnosi się to do wszystkich zarejestrowanych użytkowników.<br /> <br /> Akceptujemy następujące dokumenty: <br /> <br /> - dowód osobisty <br /> - Prawo jazdy, <br /> - Paszport. <br /> <br /> 1) Przygotuj skan dokumentu ze zdjęciem, z danymi, które potwierdzają Twoje dane na koncie w exbinog.com .<br /> 2) Przygotuj skan rachunku potwierdzającego Twój adres (rachunek za prąd, telefon, usługi komunalne). Rachunek nie może być starszy niż 3 miesiące.<br /> 3) Przygotuj skan karty użytej do depozytu. 8 cyfer z przodu oraz kod CVV z tyłu powinny zostać zakryte. <br /> <br /> Proszę przesłać dokumenty na adres payments@exbinog.com",
                cze: "In order to ensure that our Clients’ money is safe, we ask for documents confirming personal data for the first withdrawal. This applies to all the registered accounts.<br /> We accept the following documents:<br /> <br /> - personal ID,<br /> - driver’s license,<br /> - passport.<br /> <br /> 1) Please send us a scan of a document with photo and data that matches your account.<br /> 2) Please send us a utility bill confirming your address (not older than 3 months)<br /> 3) Please send us copies of both sides of the card that was used to deposit, with the 8 middle digits in the front and the CVV number at the back concealed.<br /> <br /> The documents should be scanned and sent to payments@exbinog.com .",
                ger: "In order to ensure that our Clients’ money is safe, we ask for documents confirming personal data for the first withdrawal. This applies to all the registered accounts.<br /> We accept the following documents:<br /> <br /> - personal ID,<br /> - driver’s license,<br /> - passport.<br /> <br /> 1) Please send us a scan of a document with photo and data that matches your account.<br /> 2) Please send us a utility bill confirming your address (not older than 3 months)<br /> 3) Please send us copies of both sides of the card that was used to deposit, with the 8 middle digits in the front and the CVV number at the back concealed.<br /> <br /> The documents should be scanned and sent to payments@exbinog.com .",
                rus: "In order to ensure that our Clients’ money is safe, we ask for documents confirming personal data for the first withdrawal. This applies to all the registered accounts.<br /> We accept the following documents:<br /> <br /> - personal ID,<br /> - driver’s license,<br /> - passport.<br /> <br /> 1) Please send us a scan of a document with photo and data that matches your account.<br /> 2) Please send us a utility bill confirming your address (not older than 3 months)<br /> 3) Please send us copies of both sides of the card that was used to deposit, with the 8 middle digits in the front and the CVV number at the back concealed.<br /> <br /> The documents should be scanned and sent to payments@exbinog.com .",
                spa: "In order to ensure that our Clients’ money is safe, we ask for documents confirming personal data for the first withdrawal. This applies to all the registered accounts.<br /> We accept the following documents:<br /> <br /> - personal ID,<br /> - driver’s license,<br /> - passport.<br /> <br /> 1) Please send us a scan of a document with photo and data that matches your account.<br /> 2) Please send us a utility bill confirming your address (not older than 3 months)<br /> 3) Please send us copies of both sides of the card that was used to deposit, with the 8 middle digits in the front and the CVV number at the back concealed.<br /> <br /> The documents should be scanned and sent to payments@exbinog.com .",
                por: "In order to ensure that our Clients’ money is safe, we ask for documents confirming personal data for the first withdrawal. This applies to all the registered accounts.<br /> We accept the following documents:<br /> <br /> - personal ID,<br /> - driver’s license,<br /> - passport.<br /> <br /> 1) Please send us a scan of a document with photo and data that matches your account.<br /> 2) Please send us a utility bill confirming your address (not older than 3 months)<br /> 3) Please send us copies of both sides of the card that was used to deposit, with the 8 middle digits in the front and the CVV number at the back concealed.<br /> <br /> The documents should be scanned and sent to payments@exbinog.com .",
                ita: "In order to ensure that our Clients’ money is safe, we ask for documents confirming personal data for the first withdrawal. This applies to all the registered accounts.<br /> We accept the following documents:<br /> <br /> - personal ID,<br /> - driver’s license,<br /> - passport.<br /> <br /> 1) Please send us a scan of a document with photo and data that matches your account.<br /> 2) Please send us a utility bill confirming your address (not older than 3 months)<br /> 3) Please send us copies of both sides of the card that was used to deposit, with the 8 middle digits in the front and the CVV number at the back concealed.<br /> <br /> The documents should be scanned and sent to payments@exbinog.com ."
            }

        },
        {
            name: 'bitcoin',
            canDeposit: true,
            canWithdraw: true,
            onlyInfoTextOnDeposit: true,
            onlyInfoTextOnWithdraw: true,
            order: 6,
            withdrawInfoText: {
                eng: "Please send us your BTC wallet address to payments@exbinog.com .",
                pol: "Prześlij nam Twój adres portfela w BTC na payments@exbinog.com .",
                cze: "Please send us your BTC wallet address to payments@exbinog.com .",
                ger: "Please send us your BTC wallet address to payments@exbinog.com .",
                rus: "Please send us your BTC wallet address to payments@exbinog.com .",
                spa: "Please send us your BTC wallet address to payments@exbinog.com .",
                por: "Please send us your BTC wallet address to payments@exbinog.com .",
                ita: "Please send us your BTC wallet address to payments@exbinog.com ."
            },
            depositInfoText: {
                eng: "Deposit with BTC<br /> 1) Transfer your funds to our wallet:<br /> 1B8aYse4C9kTXTft1fF4gx5Ks7RZXWkYDe<br /> 2) Send us an email with your login and the transaction amount to payments@exbinog.com .<br /> 3) The deposit will be added to your account in maximum 30 minutes. It will be calculated according to a current exchange rate from www.bitstamp.net<br />",
                pol: "Depozyt w BTC:<br /> 1) Przelej &#347;rodki na nasz portfel:<br /> 1B8aYse4C9kTXTft1fF4gx5Ks7RZXWkYDe<br /> 2) Poinformuj swojego opiekunka konta lub wy&#347;lij email na payments@exbinog.com z informacj&#261; o depozycie podaj&#261;c sw&oacute;j login i przes&#322;an&#261; kwot&#281;.<br /> 3) Depozyt zostanie przeliczony na Twoj&#261; walut&#281; konta wed&#322;ug kursu sprzeda&#380;y z www.bitstamp.net i dodany w przeci&#261;gu kilkunastu minut od momentu przelewu.<br />",
                cze: "Deposit with BTC<br /> 1) Transfer your funds to our wallet:<br /> 1B8aYse4C9kTXTft1fF4gx5Ks7RZXWkYDe<br /> 2) Send us an email with your login and the transaction amount to payments@exbinog.com .<br /> 3) The deposit will be added to your account in maximum 30 minutes. It will be calculated according to a current exchange rate from www.bitstamp.net<br />",
                ger: "Deposit with BTC<br /> 1) Transfer your funds to our wallet:<br /> 1B8aYse4C9kTXTft1fF4gx5Ks7RZXWkYDe<br /> 2) Send us an email with your login and the transaction amount to payments@exbinog.com .<br /> 3) The deposit will be added to your account in maximum 30 minutes. It will be calculated according to a current exchange rate from www.bitstamp.net<br />",
                rus: "Deposit with BTC<br /> 1) Transfer your funds to our wallet:<br /> 1B8aYse4C9kTXTft1fF4gx5Ks7RZXWkYDe<br /> 2) Send us an email with your login and the transaction amount to payments@exbinog.com .<br /> 3) The deposit will be added to your account in maximum 30 minutes. It will be calculated according to a current exchange rate from www.bitstamp.net<br />",
                spa: "Deposit with BTC<br /> 1) Transfer your funds to our wallet:<br /> 1B8aYse4C9kTXTft1fF4gx5Ks7RZXWkYDe<br /> 2) Send us an email with your login and the transaction amount to payments@exbinog.com .<br /> 3) The deposit will be added to your account in maximum 30 minutes. It will be calculated according to a current exchange rate from www.bitstamp.net<br />",
                por: "Deposit with BTC<br /> 1) Transfer your funds to our wallet:<br /> 1B8aYse4C9kTXTft1fF4gx5Ks7RZXWkYDe<br /> 2) Send us an email with your login and the transaction amount to payments@exbinog.com .<br /> 3) The deposit will be added to your account in maximum 30 minutes. It will be calculated according to a current exchange rate from www.bitstamp.net<br />",
                ita: "Deposit with BTC<br /> 1) Transfer your funds to our wallet:<br /> 1B8aYse4C9kTXTft1fF4gx5Ks7RZXWkYDe<br /> 2) Send us an email with your login and the transaction amount to payments@exbinog.com .<br /> 3) The deposit will be added to your account in maximum 30 minutes. It will be calculated according to a current exchange rate from www.bitstamp.net<br />"
            }

        },
        {
            name: 'sofort',
            canDeposit: true,
            canWithdraw: false,
            order: 5,
            depositInfoText: {
                eng: "Sofort is a global settlement system enabling internet users to conduct safe money transfers in real time. Funds will be transfered to your Exbinog account immediately. There are no fees for using this payment method. Transfers don't have a minimum and/or a maximum value. To deposit funds into your Exbinog account using Sofort, simply press deposit after entering amount you want to transfer below. You will be redirected to Sofort to complete your transaction. Please note that you must have bank account in EUR currency to use this payment method.",
                pol: "Sofort jest globalnym systemem rozliczeniowym, umożliwiającym użytkownikom przeprowadzanie bezpiecznych transferów pieniędzy w czasie rzeczywistym. Środki zostaną natychmiast przekazane na Twoje konto Exbinog. Nie pobieramy żadnych opłat za korzystanie z tej metody płatności. Transfery nie mają minimalnej lub maksymalnej wartości. Aby wpłacić pieniądze na swoje konto Exbinog używając Sofort, wystarczy nacisnąć depozyt oraz wpisać kwotę, którą chcesz zdeponować. Zostaniesz przekierowany na stronę Sofort aby zakończyć transakcję. Metoda ta dostępna jest tylko dla użytkowników posiadających konto bankowe w walucie PLN.",
                cze: "Sofort is a global settlement system enabling internet users to conduct safe money transfers in real time. Funds will be transfered to your Exbinog account immediately. There are no fees for using this payment method. Transfers don't have a minimum and/or a maximum value. To deposit funds into your Exbinog account using Sofort, simply press deposit after entering amount you want to transfer below. You will be redirected to Sofort to complete your transaction. Please note that you must have bank account in EUR currency to use this payment method.",
                ger: "Sofort is a global settlement system enabling internet users to conduct safe money transfers in real time. Funds will be transfered to your Exbinog account immediately. There are no fees for using this payment method. Transfers don't have a minimum and/or a maximum value. To deposit funds into your Exbinog account using Sofort, simply press deposit after entering amount you want to transfer below. You will be redirected to Sofort to complete your transaction. Please note that you must have bank account in EUR currency to use this payment method.",
                rus: "Sofort is a global settlement system enabling internet users to conduct safe money transfers in real time. Funds will be transfered to your Exbinog account immediately. There are no fees for using this payment method. Transfers don't have a minimum and/or a maximum value. To deposit funds into your Exbinog account using Sofort, simply press deposit after entering amount you want to transfer below. You will be redirected to Sofort to complete your transaction. Please note that you must have bank account in EUR currency to use this payment method.",
                spa: "Sofort is a global settlement system enabling internet users to conduct safe money transfers in real time. Funds will be transfered to your Exbinog account immediately. There are no fees for using this payment method. Transfers don't have a minimum and/or a maximum value. To deposit funds into your Exbinog account using Sofort, simply press deposit after entering amount you want to transfer below. You will be redirected to Sofort to complete your transaction. Please note that you must have bank account in EUR currency to use this payment method.",
                por: "Sofort is a global settlement system enabling internet users to conduct safe money transfers in real time. Funds will be transfered to your Exbinog account immediately. There are no fees for using this payment method. Transfers don't have a minimum and/or a maximum value. To deposit funds into your Exbinog account using Sofort, simply press deposit after entering amount you want to transfer below. You will be redirected to Sofort to complete your transaction. Please note that you must have bank account in EUR currency to use this payment method.",
                ita: "Sofort is a global settlement system enabling internet users to conduct safe money transfers in real time. Funds will be transfered to your Exbinog account immediately. There are no fees for using this payment method. Transfers don't have a minimum and/or a maximum value. To deposit funds into your Exbinog account using Sofort, simply press deposit after entering amount you want to transfer below. You will be redirected to Sofort to complete your transaction. Please note that you must have bank account in EUR currency to use this payment method."
            }

        },
        {
            name: 'regularwiretransfer',
            canDeposit: true,
            canWithdraw: false,
            order: 7,
            depositInfoText: {
                eng: "Deposit by Bank Wire <br> For currencies: PLN, Kč, EUR, GBP, USD, CHF.<br> <table> <tr><td>Beneficiary Name</td><td> Exclusive Ltd</td></tr> <tr><td>Beneficiary City & Country</td><td> Suites 7B & 8B Town Range, Gibraltar</td></tr> <tr><td>Bank Name</td><td> CIM BANQUE</td></tr> <tr><td>Bank Address</td><td> Rue Merle d'Aubigné 16, 1207 Geneva - Szwajcaria</td></tr> <tr><td>Swift</td><td> CIMMCHGG</td></tr> <tr><td>Account Number</td><td> 106392415</td></tr> <tr><td>IBAN</td><td> CH2508822106392415000</td></tr> </table> <br> For currencies: EUR, USD, GBP.<br> <table> <tr><td>Beneficiary Name</td><td> Exclusive Limited D.O.O.</td></tr> <tr><td>Beneficiary City & Country</td><td> Podgorica, Cetinjski put bb, Montenegro</td></tr> <tr><td>Bank Name</td><td> HIPOTEKARNA BANKA AD</td></tr> <tr><td>Bank Address</td><td> Ul.Josipa Broza Tita 67, 81000 Podgorica, Crna Gora</td></tr> <tr><td>Swift</td><td> HBBAMEPG</td></tr> <tr><td>IBAN</td><td> ME25520042000000417694</td></tr> </table> <br> Remember to put your login and/or email in the transfer title. After the transaction, send us a confirmation to payments@exbinog.com to speed up the deposit process.",
                pol: "Złóż depozyt tradycyjnym przelewem bankowym <br> Dla walut: PLN, Kč, EUR, USD, GBP, CHF.<br> <table> <tr><td>Nazwa odbiorcy</td><td> Exclusive Ltd</td></tr> <tr><td>Adres odbiorcy</td><td> Suites 7B & 8B Town Range, Gibraltar</td></tr> <tr><td>Nazwa banku</td><td> CIM BANQUE</td></tr> <tr><td>Adres banku</td><td>Rue Merle d'Aubigné 16, 1207 Geneva - Szwajcaria</td></tr> <tr><td>Swift</td><td> CIMMCHGG</td></tr> <tr><td>Numer konta</td><td> 106392415</td></tr> <tr><td>IBAN</td><td> CH2508822106392415000</td></tr> </table><br> Dla walut: EUR, USD, GBP.<br> <table> <tr><td>Nazwa odbiorcy</td><td> Exclusive Limited D.O.O.</td></tr> <tr><td>Adres odbiorcy</td><td> Podgorica, Cetinjski put bb, Montenegro</td></tr> <tr><td>Nazwa banku</td><td> HIPOTEKARNA BANKA AD</td></tr> <tr><td>Adres banku</td><td> Ul.Josipa Broza Tita 67, 81000 Podgorica, Crna Gora</td></tr> <tr><td>Swift</td><td> HBBAMEPG</td></tr> <tr><td>IBAN</td><td> ME25520042000000417694</td></tr> </table><br> Pamiętaj, aby w tytule przelewu wpisać swój login i/lub login. Po transakcji wyślij nam potwierdzenie przelewu na payments@exbinog.com w celu przyspieszenia procesu depozytu.",
                cze: "Deposit by Bank Wire <br> For currencies: PLN, Kč, EUR, GBP, USD, CHF.<br> <table> <tr><td>Beneficiary Name</td><td> Exclusive Ltd</td></tr> <tr><td>Beneficiary City & Country</td><td> Suites 7B & 8B Town Range, Gibraltar</td></tr> <tr><td>Bank Name</td><td> CIM BANQUE</td></tr> <tr><td>Bank Address</td><td> Rue Merle d'Aubigné 16, 1207 Geneva - Szwajcaria</td></tr> <tr><td>Swift</td><td> CIMMCHGG</td></tr> <tr><td>Account Number</td><td> 106392415</td></tr> <tr><td>IBAN</td><td> CH2508822106392415000</td></tr> </table> <br> For currencies: EUR, USD, GBP.<br> <table> <tr><td>Beneficiary Name</td><td> Exclusive Limited D.O.O.</td></tr> <tr><td>Beneficiary City & Country</td><td> Podgorica, Cetinjski put bb, Montenegro</td></tr> <tr><td>Bank Name</td><td> HIPOTEKARNA BANKA AD</td></tr> <tr><td>Bank Address</td><td> Ul.Josipa Broza Tita 67, 81000 Podgorica, Crna Gora</td></tr> <tr><td>Swift</td><td> HBBAMEPG</td></tr> <tr><td>IBAN</td><td> ME25520042000000417694</td></tr> </table> <br> Remember to put your login and/or email in the transfer title. After the transaction, send us a confirmation to payments@exbinog.com to speed up the deposit process.",
                ger: "Deposit by Bank Wire <br> For currencies: PLN, Kč, EUR, GBP, USD, CHF.<br> <table> <tr><td>Beneficiary Name</td><td> Exclusive Ltd</td></tr> <tr><td>Beneficiary City & Country</td><td> Suites 7B & 8B Town Range, Gibraltar</td></tr> <tr><td>Bank Name</td><td> CIM BANQUE</td></tr> <tr><td>Bank Address</td><td> Rue Merle d'Aubigné 16, 1207 Geneva - Szwajcaria</td></tr> <tr><td>Swift</td><td> CIMMCHGG</td></tr> <tr><td>Account Number</td><td> 106392415</td></tr> <tr><td>IBAN</td><td> CH2508822106392415000</td></tr> </table> <br> For currencies: EUR, USD, GBP.<br> <table> <tr><td>Beneficiary Name</td><td> Exclusive Limited D.O.O.</td></tr> <tr><td>Beneficiary City & Country</td><td> Podgorica, Cetinjski put bb, Montenegro</td></tr> <tr><td>Bank Name</td><td> HIPOTEKARNA BANKA AD</td></tr> <tr><td>Bank Address</td><td> Ul.Josipa Broza Tita 67, 81000 Podgorica, Crna Gora</td></tr> <tr><td>Swift</td><td> HBBAMEPG</td></tr> <tr><td>IBAN</td><td> ME25520042000000417694</td></tr> </table> <br> Remember to put your login and/or email in the transfer title. After the transaction, send us a confirmation to payments@exbinog.com to speed up the deposit process.",
                rus: "Deposit by Bank Wire <br> For currencies: PLN, Kč, EUR, GBP, USD, CHF.<br> <table> <tr><td>Beneficiary Name</td><td> Exclusive Ltd</td></tr> <tr><td>Beneficiary City & Country</td><td> Suites 7B & 8B Town Range, Gibraltar</td></tr> <tr><td>Bank Name</td><td> CIM BANQUE</td></tr> <tr><td>Bank Address</td><td> Rue Merle d'Aubigné 16, 1207 Geneva - Szwajcaria</td></tr> <tr><td>Swift</td><td> CIMMCHGG</td></tr> <tr><td>Account Number</td><td> 106392415</td></tr> <tr><td>IBAN</td><td> CH2508822106392415000</td></tr> </table> <br> For currencies: EUR, USD, GBP.<br> <table> <tr><td>Beneficiary Name</td><td> Exclusive Limited D.O.O.</td></tr> <tr><td>Beneficiary City & Country</td><td> Podgorica, Cetinjski put bb, Montenegro</td></tr> <tr><td>Bank Name</td><td> HIPOTEKARNA BANKA AD</td></tr> <tr><td>Bank Address</td><td> Ul.Josipa Broza Tita 67, 81000 Podgorica, Crna Gora</td></tr> <tr><td>Swift</td><td> HBBAMEPG</td></tr> <tr><td>IBAN</td><td> ME25520042000000417694</td></tr> </table> <br> Remember to put your login and/or email in the transfer title. After the transaction, send us a confirmation to payments@exbinog.com to speed up the deposit process.",
                spa: "Deposit by Bank Wire <br> For currencies: PLN, Kč, EUR, GBP, USD, CHF.<br> <table> <tr><td>Beneficiary Name</td><td> Exclusive Ltd</td></tr> <tr><td>Beneficiary City & Country</td><td> Suites 7B & 8B Town Range, Gibraltar</td></tr> <tr><td>Bank Name</td><td> CIM BANQUE</td></tr> <tr><td>Bank Address</td><td> Rue Merle d'Aubigné 16, 1207 Geneva - Szwajcaria</td></tr> <tr><td>Swift</td><td> CIMMCHGG</td></tr> <tr><td>Account Number</td><td> 106392415</td></tr> <tr><td>IBAN</td><td> CH2508822106392415000</td></tr> </table> <br> For currencies: EUR, USD, GBP.<br> <table> <tr><td>Beneficiary Name</td><td> Exclusive Limited D.O.O.</td></tr> <tr><td>Beneficiary City & Country</td><td> Podgorica, Cetinjski put bb, Montenegro</td></tr> <tr><td>Bank Name</td><td> HIPOTEKARNA BANKA AD</td></tr> <tr><td>Bank Address</td><td> Ul.Josipa Broza Tita 67, 81000 Podgorica, Crna Gora</td></tr> <tr><td>Swift</td><td> HBBAMEPG</td></tr> <tr><td>IBAN</td><td> ME25520042000000417694</td></tr> </table> <br> Remember to put your login and/or email in the transfer title. After the transaction, send us a confirmation to payments@exbinog.com to speed up the deposit process.",
                por: "Deposit by Bank Wire <br> For currencies: PLN, Kč, EUR, GBP, USD, CHF.<br> <table> <tr><td>Beneficiary Name</td><td> Exclusive Ltd</td></tr> <tr><td>Beneficiary City & Country</td><td> Suites 7B & 8B Town Range, Gibraltar</td></tr> <tr><td>Bank Name</td><td> CIM BANQUE</td></tr> <tr><td>Bank Address</td><td> Rue Merle d'Aubigné 16, 1207 Geneva - Szwajcaria</td></tr> <tr><td>Swift</td><td> CIMMCHGG</td></tr> <tr><td>Account Number</td><td> 106392415</td></tr> <tr><td>IBAN</td><td> CH2508822106392415000</td></tr> </table> <br> For currencies: EUR, USD, GBP.<br> <table> <tr><td>Beneficiary Name</td><td> Exclusive Limited D.O.O.</td></tr> <tr><td>Beneficiary City & Country</td><td> Podgorica, Cetinjski put bb, Montenegro</td></tr> <tr><td>Bank Name</td><td> HIPOTEKARNA BANKA AD</td></tr> <tr><td>Bank Address</td><td> Ul.Josipa Broza Tita 67, 81000 Podgorica, Crna Gora</td></tr> <tr><td>Swift</td><td> HBBAMEPG</td></tr> <tr><td>IBAN</td><td> ME25520042000000417694</td></tr> </table> <br> Remember to put your login and/or email in the transfer title. After the transaction, send us a confirmation to payments@exbinog.com to speed up the deposit process.",
                ita: "Deposit by Bank Wire <br> For currencies: PLN, Kč, EUR, GBP, USD, CHF.<br> <table> <tr><td>Beneficiary Name</td><td> Exclusive Ltd</td></tr> <tr><td>Beneficiary City & Country</td><td> Suites 7B & 8B Town Range, Gibraltar</td></tr> <tr><td>Bank Name</td><td> CIM BANQUE</td></tr> <tr><td>Bank Address</td><td> Rue Merle d'Aubigné 16, 1207 Geneva - Szwajcaria</td></tr> <tr><td>Swift</td><td> CIMMCHGG</td></tr> <tr><td>Account Number</td><td> 106392415</td></tr> <tr><td>IBAN</td><td> CH2508822106392415000</td></tr> </table> <br> For currencies: EUR, USD, GBP.<br> <table> <tr><td>Beneficiary Name</td><td> Exclusive Limited D.O.O.</td></tr> <tr><td>Beneficiary City & Country</td><td> Podgorica, Cetinjski put bb, Montenegro</td></tr> <tr><td>Bank Name</td><td> HIPOTEKARNA BANKA AD</td></tr> <tr><td>Bank Address</td><td> Ul.Josipa Broza Tita 67, 81000 Podgorica, Crna Gora</td></tr> <tr><td>Swift</td><td> HBBAMEPG</td></tr> <tr><td>IBAN</td><td> ME25520042000000417694</td></tr> </table> <br> Remember to put your login and/or email in the transfer title. After the transaction, send us a confirmation to payments@exbinog.com to speed up the deposit process."
            }

        }
    ]

});

CMS.constant('SkinWPConfig', {
    wpUrl: 'http://www.exbinog.com/json',  // WordpResss instance serving pages, banners
    wpBaseHost: 'www.exbinog.com',  // this parameter will be passed to JSON api and all links in response(e.g. images) will have this host,
    wpNewsUrl: {
        main: 'http://www.exbinog.com/newsjson',
        pol: 'http://www.exbinog.com/json'
    },  // WordpResss instance serving news
    wpNewsBaseHost: 'www.vbet.com',  // this parameter will be passed to JSON api and all links in NEWS response(e.g. images) will have this host
    news: {
        langRootCategories: { // IDs of root categories for each language in WordPress
            pol: '99'
        }
    }
});

CASINO.constant('SkinCConfig', {
    cUrlPrefix: 'http://games.exbinog.com',
    cGamesUrl: '/global/v-play.php',
    cUrl: '/global/casinoGamesLoad.php',
    main: {
        partnerID: '55'
    },
    login: {
        url: '/global/partners/rml.php'
    },
    balance: {
        url: '/global/cashier/cashier.php'
    }
});